import { FunctionComponent } from "react";
import styles from "./ABOUTPAGE.module.css";

const ABOUTPAGE: FunctionComponent = () => {
  return (
    <div className={styles.aboutPage}>
      <img
        className={styles.adobestock7855139081Icon}
        loading="lazy"
        alt=""
        src="/adobestock-785513908-1@2x.png"
      />
      <footer className={styles.contentWrapper}>
        <div className={styles.content}>
          <div className={styles.contentChild} />
          <img
            className={styles.complyLogo6x2}
            loading="lazy"
            alt=""
            src="/comply-logo-6x-2@2x.png"
          />
          <div className={styles.complyIsSupportedContainer}>
            <p className={styles.complyIsSupportedByTheNat}>
              ComPLy is supported by the National Institutes of Health through
              the Grant 
              <a
                className={styles.r01ag073435}
                href="https://reporter.nih.gov/project-details/10642888"
                target="_blank"
              >
                <span className={styles.r01ag0734351}>R01AG073435</span>
              </a>
            </p>
          </div>
        </div>
        <div className={styles.footer}>
          <div className={styles.footerChild} />
          <div className={styles.copyrightClinicalNlpLab}>
            © Copyright Clinical NLP Lab. All Rights Reserved
          </div>
        </div>
      </footer>
      <main className={styles.headerWrapper}>
        <header className={styles.header}>
          <div className={styles.headerChild} />
          <div className={styles.logoWrapper}>
            <div className={styles.comply1} />
            <img
              className={styles.complyLogo1}
              loading="lazy"
              alt=""
              src="/comply-logo-1@2x.png"
            />
          </div>
          <div className={styles.navigation}>
            <div className={styles.menu}>
              <div className={styles.menuLinks}>
                <a className={styles.about}>About</a>
              </div>
              <div className={styles.menuLinks1}>
                <a className={styles.phenotype}>Phenotype</a>
              </div>
              <div className={styles.searchMenu}>
                <div className={styles.resourcesMenu}>
                  <a className={styles.resources}>Resources</a>
                  <div className={styles.dropdownMenu}>
                    <img
                      className={styles.arrowDropDown24dpFill0WghIcon}
                      alt=""
                      src="/arrow-drop-down-24dp-fill0-wght400-grad0-opsz24-2-1.svg"
                    />
                  </div>
                </div>
              </div>
              <div className={styles.menuLinks2}>
                <a className={styles.contactUs}>Contact Us</a>
              </div>
              <img
                className={styles.search24dpFill0Wght400GradIcon}
                loading="lazy"
                alt=""
                src="/search-24dp-fill0-wght400-grad0-opsz24-2.svg"
              />
            </div>
          </div>
        </header>
        <section className={styles.aboutHeaderParent}>
          <div className={styles.aboutHeader}>
            <div className={styles.aboutHeaderChild} />
            <h1 className={styles.aboutComply}>About ComPLy</h1>
            <div className={styles.aboutSubtitle}>
              <h2 className={styles.transformingRealWorldData}>
                Transforming Real-World Data into Clinical Insights: Pioneering
                the Future of Disease Prevention and Treatment
              </h2>
            </div>
          </div>
          <div className={styles.features}>
            <div className={styles.featuresGrid}>
              <div className={styles.largeObservationalDataContainer}>
                <p className={styles.largeObservationalData}>
                  Large observational data from the real world, such as
                  electronic health records (EHRs) and administrative claims,
                  have become an enabling source for facilitating clinical and
                  translational research. For example, EHRs have been used to
                  support diverse studies including cohort discovery, incidence
                  characterization, onset prediction, and risk stratification,
                  demonstrating their great promise in providing new insights
                  into disease prevention and treatment. These observational
                  data based investigations have led to novel discoveries that
                  expand the horizons of traditional clinical research. Despite
                  the great promise of observational research, the quality of
                  evidence generated by these studies has sometimes been
                  questioned, due to irreproducibility, and limited effort has
                  been made to promote the “reuse” of phenotype definitions,
                  particularly in observational research.
                </p>
                <p className={styles.blankLine}>&nbsp;</p>
                <p className={styles.toPromoteThe}>
                  To promote the reuse of phenotypes in observational research,
                  we propose to develop a joint effort between medical
                  informaticians, statisticians, clinicians, and epidemiologists
                  with a focus on building a rigorous set of methods and tools
                  for managing and sharing phenotype definitions through modern
                  knowledge engineering and informatics methods.
                </p>
              </div>
              <div className={styles.searchableFeature}>
                <div className={styles.databaseFeature}>
                  <div className={styles.dataSourcesFeature}>
                    <div className={styles.dataSourcesFeatureChild} />
                    <div className={styles.aPIFeature}>
                      <div className={styles.featureIcons}>
                        <img
                          className={styles.labResearch24dpFill0Wght40Icon}
                          loading="lazy"
                          alt=""
                          src="/lab-research-24dp-fill0-wght400-grad0-opsz24-1.svg"
                        />
                        <div className={styles.updateIcons}>
                          <div className={styles.searchable}>Searchable</div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.weProvideA}>
                      We provide a searchable database of phenotype definitions
                      that can be used to support diverse studies.
                    </div>
                  </div>
                  <div className={styles.dataSourcesDescription}>
                    <div className={styles.dataSourcesDescriptionChild} />
                    <div className={styles.aPIDescription}>
                      <div className={styles.aPIIconWrapper}>
                        <div className={styles.vectorWrapper}>
                          <img
                            className={styles.vectorIcon}
                            loading="lazy"
                            alt=""
                            src="/vector.svg"
                          />
                        </div>
                        <div className={styles.multipleDataSources}>
                          Multiple Data Sources
                        </div>
                      </div>
                    </div>
                    <div className={styles.aPIDescriptionWrapper}>
                      <div className={styles.weProvidePhenotype}>
                        We provide phenotype definitions from multiple data
                        sources including PheMap, OHDSI, and PubMed.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={styles.searchableFeature1}>
                <div className={styles.frameParent}>
                  <div className={styles.rectangleParent}>
                    <div className={styles.frameChild} />
                    <div className={styles.frameWrapper}>
                      <div className={styles.update24dpFill0Wght400GradParent}>
                        <img
                          className={styles.update24dpFill0Wght400GradIcon}
                          loading="lazy"
                          alt=""
                          src="/update-24dp-fill0-wght400-grad0-opsz24-1.svg"
                        />
                        <div className={styles.livingUpdateWrapper}>
                          <div className={styles.livingUpdate}>
                            Living Update
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.weMaintainsA}>
                      We maintains a living update of phenotype definitions.
                    </div>
                  </div>
                  <div className={styles.rectangleGroup}>
                    <div className={styles.frameItem} />
                    <div className={styles.frameContainer}>
                      <div className={styles.api24dpFill0Wght400Grad0OParent}>
                        <img
                          className={styles.api24dpFill0Wght400Grad0OIcon}
                          loading="lazy"
                          alt=""
                          src="/api-24dp-fill0-wght400-grad0-opsz24-1.svg"
                        />
                        <div className={styles.apiEndpointsWrapper}>
                          <div className={styles.apiEndpoints}>
                            API Endpoints
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.weProvideApiEndpointsForContainer}>
                      <span>We provide </span>
                      <a
                        className={styles.apiEndpoints1}
                        href="https://spinup-002334.spinup.yale.edu/tripod/api_reference"
                        target="_blank"
                      >
                        <span>API endpoints</span>
                      </a>
                      <span> </span>
                      <span>
                        for programmatic access to phenotype definitions.
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default ABOUTPAGE;
